### ISSUE TITLE
请开源ravenrc.com

### ISSUE THREAD

**Issue by dou4cc** [guenchi/Raven#34]
并在[/list](http://ravenrc.com/list)的样式里加上：
```css
pre{
	word-break: break-all;
	white-space: pre-wrap;
}
```
